#数据源
spring:
  datasource:
    multiTenant: true
    schemePrefix:
    dbType: mysql
    dbVersion: 5
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.37.134:8066/jiuqi?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: cfas
    password: Mysql97!
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
      connection-test-query: select 1

  redis:
    host: 10.2.3.170
    port: 6379
    password: Redis97!
    
  rabbitmq:
    host: 10.2.37.135
    port: 5672
    username: guest
    password: guest    

#声明式客户端配置
feign:
  httpclient:
    enabled: true
  client:
    config:
      default: 
        connect-timeout: 10000
        read-timeout: 20000
      service-test:
        connect-timeout: 10000
        read-timeout: 20000

#声明式客户端所在服务信息
feignClient: 
  vmsShare:
    name: va-manage-server
    path: /vmserver
  basedataMgr:
    name: ${spring.application.name}
    path: ${server.servlet.context-path} 



